### ISSUE TITLE
Fix spec text

### ISSUE THREAD

**Issue by ljharb** [ljharb/proposal-promise-finally#2]
Current spec text uses the `finally` callback's return value as the promise resolution value (per https://github.com/ljharb/proposal-promise-finally/pull/1#issuecomment-219823021).

This needs to be fixed prior to stage 2.

**Comment by ev1stensberg** [comment]
I see invokes are being called using uppercase letters. Is this right? Such as `Ispromise` and `IsCallable`. As by your own repo, [this one](https://github.com/ljharb/is-callable), you are using lower-case. Just wanted to give you a heads-up :+1:

**Comment by ljharb** [comment]
@ev1stensberg In this case, I'm referring to spec-internal Abstract Operations. In the case of the `isCallable` repo, they're JS functions implemented in userland. The difference is intentional.
